repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-yaml

- repo: git://github.com/trussworks/pre-commit-hooks
  rev: v1.1.1
  hooks:
    - id: circleci-validate
